format = """
[](color_section1)\
$os\
$username\
[](bg:color_green fg:color_section1)\
$directory\
[](fg:color_green bg:color_section3)\
$git_branch\
$git_status\
[](fg:color_section3 bg:color_section4)\
$time\
[ ](fg:color_section4)\
$fill\
$cmd_duration\
$line_break$character"""

palette = 'onedark_warm'

[palettes.onedark_warm]
color_fg = '#191a1c'
color_section1 = '#3e4452' 
color_offwhite = '#d7dee0' 
color_section3 = '#646568' 
color_section4 = '#404247'
color_orange = '#c99a6e'
color_purple = '#c27fd7'
color_red = '#e16d77'
color_yellow = '#dfbe81'
color_blue = '#68aee8'
color_cyan = '#5fafb9'
color_green = '#98c379'

[os]
disabled = false
style = "bg:color_section1 fg:color_fg"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Macos = "󰀵"
Linux = "󰌽"
Arch = "󰣇"

[username]
show_always = true
style_user = "bg:color_section1 fg:color_fg"
style_root = "bg:color_section1 fg:color_red"
format = '[ t ]($style)'

[directory]
style = "fg:color_fg bg:color_green"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = true
#truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:color_section3 fg:color_offwhite"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:color_section3 fg:color_offwhite"
format = '[($all_status$ahead_behind )]($style)'

[time]
disabled = false
time_format = "%I:%M%P"
style = "bg:color_section4"
format = '[[  $time ](fg:color_fg bg:color_section4)]($style)'

[fill]
symbol = " "

[cmd_duration]
format = "[$duration]($style)"
min_time = 4
show_milliseconds = false
disabled = false
style = "white"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:color_offwhite)'
error_symbol = '[❯](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_offwhite)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
